### ISSUE TITLE
Firmware file

### ISSUE THREAD

**Issue by thisim** [scrool/xled#1]
Hello, is it possible to have the firmware file. I have several ESP-01 modules and I would like to order Ws2811 LED ribbons with this application.

**Comment by scrool** [comment]
Hello, I guess you could ask [Twinkly](http://twinkly.com/) customer support. This project is no way supported by Ledworks. I'm afraid I cannot redistribute the firmware unless I'm told or find otherwise.

**Comment by thisim** [comment]
OK thanks anyway. I will contact them, but I do not think they agree. Otherwise, in MP is what it would be possible (like that, the firmware would not be available to everyone). My email is: simonthierry@free.fr
