### ISSUE TITLE
Firmware 2.1 Login process changed?

### ISSUE THREAD

**Issue by mrswadge** [scrool/xled#10]
Attempted to follow https://xled-docs.readthedocs.io/en/latest/rest_api.html#login, but when I issue a challenge I get an 1106 status code back from the lights. 

I've attempted to packet sniff via Wireshark against a local android emulator running in Android Studio, but I couldn't get it to see the lights via the Twinkly app. I could however do the http://\<ip\>/xled/v1/gestalt URL, so it can definitely see the lights if you know where to look. 

Any further ideas what to do to investigate how the login works now?

Cheers,
Stuart

**Comment by mrswadge** [comment]
I think the reason the lights are not found from the application via the emulator is because there is a limitation with multicast messaging in the emulator. 😞 

https://developer.android.com/studio/run/emulator-networking

**Comment by scrool** [comment]
I don't think login process changed. I'm still able to use lights with [xled](https://xled.readthedocs.io/en/latest/readme.html).

**Comment by mrswadge** [comment]
I think you are right. I was using Postman to test, but it is behaving differently to my wget command. I think this issue can be closed. 

Cheers,
Stuart
