### ISSUE TITLE
Xled_plus - use xled to produce various effects

### ISSUE THREAD

**Issue by Anders-Holst** [scrool/xled#108]
This is not really an issue, but rather an announcement:
I have moved out my proposed xled additions (previously in pull request #80) into its own repository [xled_plus](https://github.com/Anders-Holst/xled_plus). It adds features on top of xled for creating different types of effects on your lights, removing the need to use the (rather limited and awkward) app for that.

There is a discussion forum there too, which we can use to discuss both xled and xled_plus things (which doesn't fit better here as issues of course). I will, as a kind of "advent calendar", publish daily effects there, starting tomorrow Dec 1.

You are welcome to check it out!

**Comment by scrool** [comment]
> [...] into its own repository xled_plus.

Correct link: https://github.com/Anders-Holst/xled_plus

**Comment by Anders-Holst** [comment]
Sorry for the mistake and thanks for spotting it! I have edited the post now so it is correct.

**Comment by scrool** [comment]
Repository xled_plus is now referenced from xled-docs, similarly to other [Client implementations](https://xled-docs.readthedocs.io/en/latest/readme.html#client-implementations) and discussion with daily effects is listed under [Communities on the same site](https://xled-docs.readthedocs.io/en/latest/readme.html#communities). I'm going to close this announcement which we had here for few months now so hopefully it served its purpose.
