### ISSUE TITLE
Documentation is rendered incorrectly (inconsistently) on read the docs

### ISSUE THREAD

**Issue by scrool** [scrool/xled#111]
**GitHub** renders block fine:

![xled readme github](https://user-images.githubusercontent.com/27489/144124519-f9d281fa-38f0-45e7-93e2-9ad61301277c.png)

---

**Local** run of **Sphinx** the same:

![xled readme sphinx](https://user-images.githubusercontent.com/27489/144124558-26749b3e-f818-49a2-a4a0-cd0b03ba2084.png)

---

Even on **PyPI** it renders fine:

![xled readme pypi](https://user-images.githubusercontent.com/27489/144125491-0b1d69c2-bec2-46aa-be66-8a3f033e19e1.png)

---

But on **Read the Docs** it is missing code blocks:

![xled readme readthedocs](https://user-images.githubusercontent.com/27489/144124596-f6e15590-0318-4cad-9074-6b4293aa1a7b.png)

---

Problematic section:
```
Installation
------------

Both library and CLI tool are supported on Linux, primarily Fedora.

#. First make sure that you have `pip installed`_. E.g. for Fedora:

   ::

       $ sudo dnf install python3-pip python3-wheel

#. You might want to `create and activate a virtual environment`_. E.g.:

   ::

       $ mkdir -p ~/.virtualenvs
       $ python3 -m venv ~/.virtualenvs/xled
       $ source ~/.virtualenvs/xled/bin/activate

#. Install `xled from PyPI`_:

   ::

       $ python3 -m pip install --upgrade xled
```

**Comment by Anders-Holst** [comment]
Hypothesis, without having checked: Maybe dollar is considered a comment sign? Can it be quoted with backslash, or will that break the other destinations? If, so, maybe switch the shell prompt, from "$" to for example "shell>".

**Comment by scrool** [comment]
Hmm. Now https://xled.readthedocs.io/en/latest/readme.html#installation shows code just fine. I guess it was cached in my browser from some previous attempts.
