### ISSUE TITLE
Question - using MAC address rather than Discovery

### ISSUE THREAD

**Issue by PaulWebster** [scrool/xled#14]
This is a question rather than an issue.
I have been experimenting with using CLI from shell scripts and it is working well.
However, the discovery process seems to take between 2 and 4 seconds ... so I modified cli.py to support passing in a MAC address ... and if the host address (ip address) and new mac address are given on the command line then I skip the discovery phase and use the given parameters.
This does mean that the device name is not known as a result of discovery ... but are there any other consequences that you can think of that could cause problems?
For cli it is a fire once and exit function - so the background discovery functionality should not matter.
Of course, the user might get the parameters incorrect - but that is easily fixed by the user.

**Comment by scrool** [comment]
> This does mean that the device name is not known as a result of discovery ... but are there any other consequences that you can think of that could cause problems?

There isn't any hidden state passed from discover to HighControlInterface. So no, there shouldn't be any other consequences.

**Comment by PaulWebster** [comment]
I might have found one issue.
I think there is something happening in background after discovery is called ... because if the same task calls discovery again then I get an error saying that the port is already in use.
(running on Raspberry Pi/Raspbian (Debian like))

**Comment by scrool** [comment]
I haven't seen how you have changed the code nor the traceback. Could you show me those?

**Comment by PaulWebster** [comment]
Sure - although the code change is not directly related.
Here is an example with original xled installed by pip3
(note though - I had to build and install zmq because pip3 could not do it)

```
import xled
import time

tw_hw_address, tw_device_name, tw_ip_address = xled.discover.discover()

print("Found:" + str(tw_device_name))

time.sleep(10)

tw_hw_address, tw_device_name, tw_ip_address = xled.discover.discover()

```

```
python3 tracexled.py
Found:b'Twinkly_B6A06E'
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.4/dist-packages/xled/discover.py", line 313, in start
    self.udp.handle.fileno(), self.handle_beacon, self.loop.READ
  File "/usr/local/lib/python3.4/dist-packages/xled/udp_client.py", line 55, in handle
    _handle.bind(("", self.port))
OSError: [Errno 98] Address already in use




^CTraceback (most recent call last):
  File "debugxled.py", line 12, in <module>
    tw_hw_address, tw_device_name, tw_ip_address = xled.discover.discover()
  File "/usr/local/lib/python3.4/dist-packages/xled/discover.py", line 65, in discover
    response = interface.recv()
  File "/usr/local/lib/python3.4/dist-packages/xled/discover.py", line 162, in recv
    return self.pipe.recv_multipart()
  File "/usr/local/lib/python3.4/dist-packages/zmq/sugar/socket.py", line 467, in recv_multipart
    parts = [self.recv(flags, copy=copy, track=track)]
  File "zmq/backend/cython/socket.pyx", line 788, in zmq.backend.cython.socket.Socket.recv
  File "zmq/backend/cython/socket.pyx", line 824, in zmq.backend.cython.socket.Socket.recv
  File "zmq/backend/cython/socket.pyx", line 186, in zmq.backend.cython.socket._recv_copy
  File "zmq/backend/cython/checkrc.pxd", line 12, in zmq.backend.cython.checkrc._check_rc
KeyboardInterrupt
```

**Comment by scrool** [comment]
You don't really need to run discover if you know MAC address (and IP address) of your device. Instead you could just rewrite https://github.com/scrool/xled/blob/develop/xled/cli.py#L27 in a way that would accept these two addresses.

I guess there could be a bug in the discovery code that doesn't close socket that it uses to send messages.

**Comment by PaulWebster** [comment]
Sure - and that is what I have done. I will send you my changes to review etc.
Was just pointing out something odd. Might be worth adding something in documentation to say that (for now at least) discovery should not be called twice by same running instance.

**Comment by scrool** [comment]
I believe 862580c fixes the issue with discovery not closing its socket.

**Comment by PaulWebster** [comment]
FYI - I did submit a pull request to add this - but would you prefer that I issued that against dev rather than release?
https://github.com/scrool/xled/pull/17

**Comment by scrool** [comment]
Ah, I'm sorry I was travelling at that time and I totally forgot about that PR. I haven't had a chance to review this and try it.

In general yes, it would be better to base it against develop branch rather than master one.

**Comment by PaulWebster** [comment]
Have now resent the pull request but against "develop" this time.

**Comment by scrool** [comment]
With #63 in place it should be enough to specify IP address/hostname. Same functionality will be done with #61. Therefore I'm going to close this one.
