### ISSUE TITLE
music dongle support?

### ISSUE THREAD

**Issue by wkearney99** [scrool/xled#148]
Does the API provide a way to toggle the USB music dongle on/off?  It's their standalone mic, that picks up ambient sound (presumably from music playing nearby) and uses that to influence patterns on the lights.  It'd be great to have on/off control of it.  

The strips will fall back to using their saved playlist of lighting effects if the music is turned off.

**Comment by scrool** [comment]
Unfortunately I don't have USB music dongle and I don't know answer to this either. You could try to reach out to other [communities around Twinkly](https://xled-docs.readthedocs.io/en/latest/readme.html#communities) or some actively developed [Client implementations](https://xled-docs.readthedocs.io/en/latest/readme.html#client-implementations), e.g. Artnet 2 Twinkly.
