### ISSUE TITLE
Discovery wit multiple devices

### ISSUE THREAD

**Issue by wackazong** [scrool/xled#15]
Can you give an example of how to discover multiple devices please? Names/MAC/IP data is not known.

**Comment by scrool** [comment]
Are you asking about CLI or the library?

**Comment by wackazong** [comment]
The library

**Comment by scrool** [comment]
You can use `xled.discover.xdiscover()` for that.

**Comment by wackazong** [comment]
Yeah, but that returns only one device, right? What if I want to get all devices on the network?

**Comment by scrool** [comment]
`xdiscover()` is an generator that will scan for all devices up. I have just pushed that one to complement `discover()` which returns first device.

**Comment by wackazong** [comment]
Ah, didnt find it in the doc and thought its a typo. Cool, thanks! I will have a look if I can get it to work on OS X.
