### ISSUE TITLE
Using xled on OS X

### ISSUE THREAD

**Issue by wackazong** [scrool/xled#16]
Install on OS X fails:

use of undeclared identifier 'SIOCGIFHWADDR'

Is this a known issue?

**Comment by scrool** [comment]
I'm afraid I cannot test this on OS X so I cannot say if it could work at all.

**Comment by wackazong** [comment]
Ok. So this library is developed for Linux? I did not see a platform requirement in the Readme.

**Comment by scrool** [comment]
Yep, I have tested that only on Linux.
