### ISSUE TITLE
Compatibility for OS X

### ISSUE THREAD

**Issue by wackazong** [scrool/xled#18]
Hey, I found a way to use the library on Mac, didn't I send you a pull request? I would offer to test and maintain this package for Mac if that's ok with you.

**Comment by scrool** [comment]
Is that this commit? https://github.com/wackazong/xled/commit/ba7757d3679d645fdeacc16674ee51cb24a7ee20

**Comment by wackazong** [comment]
Yes, and the next one for the requirements in setup.py

**Comment by scrool** [comment]
I haven't tried that on Linux but if it that would work I guess it is good idea to have an alternative implementation. On homepage for getmac I read that it could work on both Mac and Windows so other people could benefit from this. On the other hand I wouldn't be able to fully support those other platforms. I'm thinking of conditional requires according to operating system.

**Comment by wackazong** [comment]
Why not use getmac for all platforms? It says it’s pure python, platform-independent implementation.

**Comment by scrool** [comment]
Well I have read this in [the documentation](https://pypi.org/project/get-mac/):

> If the only system you need to run on is Linux, you can run as root, and C-extensions modules are fine, then you should instead check out the arpreq package by Sebastian Schrader. It can be significantly faster, especially in the case of hosts that don't exist (at least currently).

**Comment by wackazong** [comment]
Ok, I see. Well, conditional requires are the way to go then I guess.
