### ISSUE TITLE
Error in error handler

### ISSUE THREAD

**Issue by wackazong** [scrool/xled#29]
https://github.com/scrool/xled/blob/69ce41aad5ac449953b3b9ecccdba0cbb7f886ca/xled/response.py#L69

`
  File "/home/pi/wakeupcall/.venv/src/xled/xled/response.py", line 69, in data
    raise ApplicationError(msg, response=self.response)
  File "/home/pi/wakeupcall/.venv/src/xled/xled/exceptions.py", line 6, in __init__
    super(XledException, self).__init__(*args, **kwargs)
TypeError: ApplicationError() takes no keyword arguments
`

**Comment by timon** [comment]
#35 addresses this issue.
@wackazong  could you give it a try?

**Comment by wackazong** [comment]
Yes, this fixes my problem. Thanks.
