### ISSUE TITLE
Packet Capture for Gen 2 750 Light Tree

### ISSUE THREAD

**Issue by MizterB** [scrool/xled#51]
For reference, I am sharing a Wireshark packet capture between the iOS Twinkly app and my Gen 2 750 light RGB Christmas tree.  This capture includes the app launch, editing a solid color effect (rt mode), then applying that effect as a movie.

My primary reason for sharing is because I believe the realtime UDP protocol has changed, or at least is different for such a a large number of lights.  I believe the movie API may have changed a bit as well.  

I'm hoping that anyone who understands the code but does not have access to this kinds of device might be able to improve the documentation and code to support newer devices and firmware.

[Twinkly Gen 2 750 Lights - App Launch & Effect Change.pcapng.zip](https://github.com/scrool/xled/files/5612391/Twinkly.Gen.2.750.Lights.-.App.Launch.Effect.Change.pcapng.zip)

**Comment by MizterB** [comment]
Regarding the realtime UDP packet changes, I observed the following after comparing multiple captures:

- There appears to be a 12-byte header for each packet
- There are up to 300 RGB light definitions in each packet.  For my 750 lights, this means 3 packets to send the info, with the following sizes:
```
912 (12 + 300*3)
912 (12 + 300*3)
462 (12 + 150*3)
```
The header structure looks like this across 3 different captures:
```
01 02 03 04 05 06 07 08 09 10 11 12
-- -- -- -- -- -- -- -- -- -- -- ----------
03 be c3 81 b1 e4 fe f4 db 00 00 [00|01|02]
03 2c ec 9d b2 fa 9a 2b 81 00 00 [00|01|02]
03 dc 92 f9 cb e5 0e b6 42 00 00 [00|01|02]
```
I am guessing that this corresponds to the following:
- Byte 1: Total number of packets in the message (in my case, always 3)
- Bytes 2-9: The 8 byte Base 64 decoded authentication token
- Bytes 10-11: Always 0
- Byte 12: Offset for the light definition.  For example, 0 means the packets describes lights 1-300, 1 means lights 301-600, 2 means lights 601-900, etc....

**Comment by scrool** [comment]
There seems to be something missing at the very beginning of the authentication handshake - between 4th and 6th packet.

And then later when modes are switched - packets 12 and 13.

**Comment by Walderbash** [comment]
My 250 lights Gen2 Special edition sends almost the same format, only difference is the color is sent as 4 bytes, starting with white, and because of that the pages are smaller, only 225 lights per packet. So packet one is 912 bytes for 225 lights, packet two 112 bytes for the last 25 lights.

here are the header bytes for white light packets one and two, and header bytes for red light:
```
 1 start - 8 token - 3 offset - 4 WRGB 4 WRGB
03 30b6ebfc4243a7f8 000000 ff000000 ff000000 ff000000
03 30b6ebfc4243a7f8 000001 ff000000 ff000000 ff000000
03 30b6ebfc4243a7f8 000000 00ff0000 00ff0000 00ff0000
```

**Comment by scrool** [comment]
New versions of RT modes have been documented - https://xled-docs.readthedocs.io/en/latest/protocol_details.html#real-time-led-udp-packet-format and now they are supported by the library since a8e8036f2bd9ab32381ea92d94ddb81b7050477e .

I'm closing this out as done.
