### ISSUE TITLE
Device polling

### ISSUE THREAD

**Issue by d4rkmen** [scrool/xled#55]
Hi, guys
Not an issue of this library (btw, I like the old single file version more, now it become a monster) but the `xled` protocol itself.
The problem happen with device polling (check mode and brightness from time to time). It kills mobile app session because of auth token changed. This way its not possible to setup new effects etc when some smarthome controller polling the device.
Any ideas?

**Comment by scrool** [comment]
A device support one and only one active session. There is nothing that this library could do about that. It depends how you use this though - your application could be more resilient to temporary failures of authentication.

PS: there wasn't ever single file version. The very first public version dae9fcfe7550676c226fc9dd8c88df100a559877 consisted of couple of modules in a python package.

**Comment by d4rkmen** [comment]
> your application could be more resilient to temporary failures of authentication.

Yes, the problem with Twinkly App mostly



> PS: there wasn't ever single file version

Sorry, i thought it was yours https://labs.f-secure.com/blog/twinkly-twinkly-little-star/ (Appendix 0x01)

I am now looking in `MQTT` control. It does not mess with auth token

**Comment by scrool** [comment]
> Yes, the problem with Twinkly App mostly

I cannot affect Twinkly App behavior at all.

> I am now looking in MQTT control. It does not mess with auth token

Ok. I'm going to close this issue then.
