### ISSUE TITLE
Get MAC address from `gestalt`

### ISSUE THREAD

**Issue by scrool** [scrool/xled#59]
Fall back to mac address reported by device itself in `gestalt` API as an alternative to `arpreq` or `getmac`.

**Comment by PaulWebster** [comment]
See also my old pull request that adds an optional command line parameter to pass in the mac address.
My guess is that most people do not have frequently changing set-ups so being able to avoid the discovery phase can speed up single shot commands.
https://github.com/scrool/xled/pull/19

**Comment by scrool** [comment]
#63 has been merged.

Slightly different approach that I got on my mind - to provide a fallback. It turned out that we can't use ARP in Gen II to verify of challenge responses.
