### ISSUE TITLE
locale.nl_langinfo(locale.T_FMT) unsupported on Windows.

### ISSUE THREAD

**Issue by Emerica** [scrool/xled#60]
nl_langinfo seems to be unsupported on Windows.

More curious on how you'd like to see this approached.
It's used at least in get-timer to format the times.

```
if sys.platform == 'win32':
    format = "%H:%M:%S"
else:
    format = locale.nl_langinfo(locale.T_FMT)
```
Thoughts appreciated.

**Comment by scrool** [comment]
I'm sorry but Windows is not supported. Rather than this special win32 code I'm thinking of using hardcoded format.

**Comment by Emerica** [comment]
That's why I'm asking, or an option with format string and a default?
