### ISSUE TITLE
Discovery when multiple interfaces are present

### ISSUE THREAD

**Issue by timon** [scrool/xled#69]
This might be related to #61 

I'd like to use `xled` with Home Assistant, and for that I consder using autodiscovery.
My setup is  Raspberry PI which is connected to home automation WiFi. and also a regular ethernet, and Twinkly that is registered in the home automation WiFi.

It appears to me that the discovery process is running only on one interface: if both interfaces are up, `xled.discover.discover()` takes a long time (and I have stopped it with ^C). Unplugging the ethernet cord resulted in a quick response from my twinkly.

I think that the discoverer should try all running interfaces.

P.S. I could try implementing this myself if you could provide me with outline how this could be achieved

**Comment by scrool** [comment]
This is strange. I do use discovery on a laptop with two network interfaces as well and it works just fine.

Have you checked your firewall? Only after I filed #61 I have found that my laptop used firewalld with Public zone active. Which doesn't accept incoming packets to UDP/5555.

How about priorities in routing table (what's output of `ip route`)?

Does it behave the same way if you disconnect from WiFi but keep your ethernet on? (I assume that you can access your twinkly through some WiFi access point).

Could you try to run this with DEBUG verbosity?

Especially recently I have found that application not only uses 255.255.255.255 but also network specific broadcasts, e.g. 192.168.0.255 and finally it tries even 192.168.4.1 directly. I think this approach might need external library to enumerate interfaces, its network addresses and finally send it over broadcasts.

**Comment by timon** [comment]
Thanks a lot for your suggestions!

> Have you checked your firewall?

This is a raspberry PI, I don't have firewall enabled nor installed

> How about priorities in routing table (what's output of ip route)?

This seems to be the catch, I have two default routes:

```
default via 172.16.17.1 dev eth0 proto dhcp src 172.16.17.175 metric 202 
default via 172.16.18.1 dev wlan0 proto dhcp src 172.16.18.2 metric 303 
172.16.17.0/24 dev eth0 proto kernel scope link src 172.16.17.175 metric 100 
172.16.17.0/24 dev eth0 proto dhcp scope link src 172.16.17.175 metric 202 
172.16.18.0/24 dev wlan0 proto dhcp scope link src 172.16.18.2 metric 303 
```

172.16.18.1/24 is the automation WiFI, 172.16.17.1 is the regular network

> Does it behave the same way if you disconnect from WiFi but keep your ethernet on? (I assume that you can access your twinkly through some WiFi access point).

Yes, it does: no device gets discovered (this is kinda expected). Discovery works like a charm if the only enabled interface is WiFi

> Could you try to run this with DEBUG verbosity?

```
DEBUG:xled.discover:Starting Agent
DEBUG:xled.discover:Starting Loop
DEBUG:xled.discover:Sending ping
DEBUG:xled.discover:Waiting for a beacon.
DEBUG:xled.discover:Ignoring ping message received from network from 172.16.17.175.
```
The last three lines (Sending ping - Waiting for a beacon - Ignoring ping message) are repeated.

**Comment by scrool** [comment]
> I'd like to use xled with Home Assistant, and for that I consder using autodiscovery.

I believe you could use integration that is (for some time now) in official Home Assistant distribution - https://www.home-assistant.io/integrations/twinkly/ . I wasn't able to reproduce this nor I saw a traction from anybody else. I'm going to close this issue now.
