### ISSUE TITLE
get_mode() always returns ApplicationResponse[None]

### ISSUE THREAD

**Issue by samstreak** [scrool/xled#7]
Trying to create a toggle function but in order to do this, need to get the current state. I am able to set_mode('movie') or set_mode('off'), but unable to read the state.

`import os
import xled

hosts = ['192.168.2.196']

for host in hosts:
    response = os.system('ping ' + host + ' -n 1 -w 250|find /i "TTL=" /c')
    if response == 0:
        print('Checking ' + host + '...')
        control = xled.ControlInterface(host)
        print(control.get_mode())
`
returns:
Checking 192.168.2.196...
<ApplicationResponse [None]>

interactive in Python 2.7 brings the same "None" response as well.

**Comment by scrool** [comment]
`control.get_mode()['mode']` will print the current mode.
