### ISSUE TITLE
Error: Only one usage of each socket address

### ISSUE THREAD

**Issue by bigboss97** [scrool/xled#74]
I'm new here. I'm using Miniconda virtual environment. When I ruan following command it got frozen:
```
(xled) PS C:\Users\home> xled on
Looking for any device...
```
When I tried to specify the name of the device I got this:
```
(xled) PS C:\Users\home> xled --name Twinkly_71B12D on
Looking for a device with name: Twinkly_71B12D...
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\home\AppData\Local\Programs\Python\Python37\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Users\home\AppData\Local\Programs\Python\Python37\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\home\AppData\Local\Programs\Python\Python37\lib\site-packages\xled-0.6.1-py3.7.egg\xled\discover.py", line 370, in start
    self.udp.handle.fileno(), self.handle_beacon, self.loop.READ
  File "C:\Users\home\AppData\Local\Programs\Python\Python37\lib\site-packages\xled-0.6.1-py3.7.egg\xled\udp_client.py", line 59, in handle
    _handle.bind(("", self.port))
OSError: [WinError 10048] Only one usage of each socket address (protocol/network address/port) is normally permitted
```
I've googled a bit and I saw something to do with port already used by other application. Any suggestion how to fix this?
Thanks in advance.

**Comment by scrool** [comment]
Please make sure that you run the application only once. It is not created to support multiple invocations at the same time.

**Comment by bigboss97** [comment]
Thanks for the response. You're right. That happened if I leave the hung terminal open and run command in another window.
I still can't get any command to return. I can ping the Twinkly lights from my conda terminal.
I followed:
https://xled.readthedocs.io/en/latest/contributing.html?highlight=get%20started#get-started
But I didn't do clone. I simply downloaded the files and ran:
```
(base) E:\work\python\xled-develop>pip install -r requirements_dev.txt
(base) E:\work\python\xled-develop>python setup.py develop
```
Have I missed anything? My python version is 3.7.5.

**Comment by scrool** [comment]
@bigboss97 if you haven't given up yet, try to enable logging before you run your commands. With CLI it means use of options `--verbosity-cli DEBUG --verbosity-discover DEBUG --verbosity-control DEBUG --verbosity-auth DEBUG`.

I haven't tested code on Windows nor I'm able to support it though. It was intended to be run on Linux only.

**Comment by bigboss97** [comment]
Thanks for your help.

I've tried to write my own codes. Eventually, I got something to work, see here:
https://youtu.be/FyVJZMsM0zM
