### ISSUE TITLE
Writing firmware

### ISSUE THREAD

**Issue by PaulWebster** [scrool/xled#8]
I have an issue with the current Twinkly app version 1.5.2 (build 478) when controlling my LED string.
The LEDs are running firmware version 1.99.10 (older than yours) and the app refuses to map the LEDs because the firmware is too old.
However, the firmware update fails because the app times out before the response to the firmware update completes.
I reported it to Twinkly last week - but so far have no solution.

So ... I am thinking about using your xled to do the firmware write (I have captured what the official app was trying to upload and my SHA1 checksums for the captured data matches what the LEDs return in the fw update response).

Given that writing firmware could go horribly wrong ... I would like to know if that function in your xled has  library has been tested.
For example - it does not appear to set "Content-Type: application/octet-stream" via
headers={'Content-Type': 'application/octet-stream'}
Is that because it is not needed - or is it untested?

The comment in the upload fw routines say that "firmware" parameter is a "file-like object that points to firmware file".
So should I pass in the name of a file?

**Comment by PaulWebster** [comment]
UPDATE:
I just updated my firmware ... now running 2.0.22-mqtt ...

Needs a small change to control.py to put a "checksum" around the json_payload
so it becomes
```
json_payload = {'checksum':{
            'stage0_sha1sum': stage0_sha1sum,
            'stage1_sha1sum': stage1_sha1sum,
        }}
```
Without you get an error response of 1104 (so you can also add that to the list of seen responses) - perhaps indicates malformed JSON.

Not necessary to specify "headers={'Content-Type': 'application/octet-stream'}" (I did it for fw/0 but not for fw/1 and it worked).
Also - no need to apply a timeout - it looks like the Python defaults are enough.

The "firmware" parameter hold the contents of the files - so I read them in binary mode before making the call and passed in the content as the parameter.

I made lots of changes to control.py while I was trying to use it ... and my guess is that some of them were not really needed ... but it means that I probably should not submit it as a patch.

Note - I was using Python 3.6 on Windows - so that might have introduced some of the issues that I faced.
For example - I had to add a .decode() to the b64_challenge in send_challenge (challenge_response_auth.py) to force it to a string.
I also had to change lots of the asserts that were checking for [u'code] or similar to ['code'] because otherwise they were not working for me.

Now off to see if 2.0.22-mqtt works with the Twinkly app ...

**Comment by scrool** [comment]
Hey Paul!

Firstly thanks for trying to update the firmware and I'm glad it worked.

Frankly I haven't tested upload of firmware for the very same reason - I wasn't sure if documentation was complete and I didn't want to brick my device.

I haven't throughtfully tested the code on Python 3 and unit tests are far from optimal. I hope those asserts and issues with unicode will be caught in the future.

**Comment by scrool** [comment]
I was able to update firmware with new changes: 202959e625bb44a8263ddd1e60de7173c297aaf1 so I'm marging this one as resolved.

**Comment by PaulWebster** [comment]
Excellent. I just saw the cli code as well. Will make it very easy for others to incorporate into scripts.

**Comment by wackazong** [comment]
@scrool and @PaulWebster would you have firmware files I could use lying around somewhere? I would like to try and update my Twinklys to the latest firmware but in the case it does not work I would love to have some compatible firmware to downgrade to...

**Comment by PaulWebster** [comment]
Yes - although there are two generations of devices I think so not 100% certain that same firmware on both.

**Comment by wackazong** [comment]
Yes, there are two generations now. I have two first generation devices. It should fit. You can write me an email: alexander@wackazong.com

**Comment by scrool** [comment]
@wackazong firmware is always part of Android's apps. So just search for Google Play mirrors that archive that app.
