### ISSUE TITLE
"get" Commands Not Functioning As Expected

### ISSUE THREAD

**Issue by noremac00662006** [scrool/xled#87]
I have a strand of Twinkly lights (Model TWS250STP-GUS) that I wanted to try this API on however I can not get a simple "get" to function as intended. The light strand is connected to same Wi-Fi network as the Raspberry Pi and I can get requests such as "set_mode()", "set_brightness()", "turn_off()" and "turn_on()" to work however when I try "is_on()", the code always returns the except statement "Could not determine".  I can not figure out how to get it to return "True" or "False". Code provided below:

import xled
host = ip_address #Redacted
def LightState():
    try:
        State = xled.HighControlInterface(host)
        Power_State = State.is_on()
        return Power_State
    except:   
        return "Could not determine"
print (LightState())

I run into the same issue with "get_mode", "get_device_info()" or "get_device_name()". Reading through the documentation, I saw this specific product was not listed in hardware however I wanted to make sure I was not missing anything.

**Comment by Anders-Holst** [comment]
There is an example snippet of python commands quite early in the README.rst file of this repository. If you run those commands one at a time, where exactly does it go wrong and with what error message?

**Comment by noremac00662006** [comment]
Sorry for the late reply as I was on travel. Using the example code from the README.rst file, the code breaks at "discovered_device.name". The error I get is posted below.

Exception has occurred: AttributeError
'DiscoveredDevice' object has no attribute 'name'

**Comment by Anders-Holst** [comment]
Embarrassing, it should have said discovered_device.id in the example... It should be fixed in README.rst.
However, that is probably not related to your problem. If you continue with the lines below, what happens then?
(You may even skip the "set_mode" call and jump directly to "get_mode" and "get_device_info" - the ones you say does not work. But the line before, creating the ControlInterface is important though.)

**Comment by scrool** [comment]
@noremac00662006 you could enable logging to find out what is going on. Before all your code add following:

```python
import logging
log = logging.getLogger()
log.setLevel(logging.DEBUG)
ch = logging.StreamHandler()
ch.setLevel(logging.DEBUG)
ch.setFormatter(logging.Formatter('%(name)s - %(levelname)s - %(message)s'))
log.addHandler(ch)
```
---

Thanks for pointing out a bug in the documentation. I have fixed that.

**Comment by noremac00662006** [comment]
I ran the code again with logging enable (shown below):
``` python
import logging
log = logging.getLogger()
log.setLevel(logging.DEBUG)
ch = logging.StreamHandler()
ch.setLevel(logging.DEBUG)
ch.setFormatter(logging.Formatter('%(name)s - %(levelname)s - %(message)s'))
log.addHandler(ch)


import xled
discovered_device = xled.discover.discover()
discovered_device.name
control = xled.ControlInterface(discovered_device.ip_address, discovered_device.hw_address)
control.get_mode()['mode']
```
I get the following error on "discovered_device.name":

Exception has occurred: AttributeError
'DiscoveredDevice' object has no attribute 'name'

Below is the output from the logging:

asyncio - DEBUG - Using selector: EpollSelector
xled.discover - DEBUG - Starting Agent
asyncio - DEBUG - Using selector: EpollSelector
xled.discover - DEBUG - Starting Loop
xled.discover - DEBUG - Sending ping
xled.discover - DEBUG - Waiting for a beacon.
xled.discover - DEBUG - Ignoring ping message received from network from 10.0.0.29.
xled.discover - DEBUG - Waiting for a beacon.
xled.discover - DEBUG - Received a beacon from 10.0.0.43.
xled.discover - DEBUG - Received b'+\x00\x00\nOKTwinkly_713D85\x00'
xled.discover - DEBUG - Getting hardware address of b'10.0.0.43'.
xled.discover - DEBUG - Never seen b'98:f4:ab:71:3d:84' before.
xled.discover - DEBUG - Going to send [b'JOINED', b'98:f4:ab:71:3d:84', b'Twinkly_713D85', b'10.0.0.43'].
xled.discover - DEBUG - Stopping Agent thread.
xled.discover - DEBUG - Stopping periodic ping.
xled.discover - DEBUG - Removing beacon handler.
xled.discover - DEBUG - Closing UDP client.
xled.discover - DEBUG - Stopping loop from agent
xled.discover - DEBUG - Waiting for Agent thread to join us.
xled.discover - DEBUG - Loop ended
xled.discover - DEBUG - Closing main thread part of the pipe
xled.discover - DEBUG - Closing agent thread part of the pipe
xled.discover - DEBUG - Terminating context
xled.discover - DEBUG - Stopping Agent thread.
xled.discover - DEBUG - Stopping periodic ping.
xled.discover - DEBUG - Removing beacon handler.
xled.discover - DEBUG - Closing UDP client.
xled.discover - DEBUG - Stopping loop from agent
xled.discover - DEBUG - Waiting for Agent thread to join us.
xled.discover - DEBUG - Closing main thread part of the pipe
xled.discover - DEBUG - Closing agent thread part of the pipe
xled.discover - DEBUG - Terminating context

**Comment by Anders-Holst** [comment]
And again, as I said above, "discovered_device.name" is a typo in the README file, the interesting stuff comes after it. So please run again but omit that very line this time.

**Comment by scrool** [comment]
@noremac00662006 could you post output of `http://10.0.0.44/xled/v1/gestalt` ? (preferrably quote that with https://docs.github.com/en/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code )

**Comment by scrool** [comment]
And on the top of that - please try to run that code again and make sure that you don't have application on your phone opened.

**Comment by noremac00662006** [comment]
> @noremac00662006 could you post output of `http://10.0.0.44/xled/v1/gestalt` ? (preferrably quote that with https://docs.github.com/en/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code )

Sorry this is my first time using github. Please let me know if I have posted the output in the right format.

```
{
  "product_name": "Twinkly",
  "hardware_version": "302",
  "bytes_per_led": 3,
  "hw_id": "60ea00",
  "flash_size": 64,
  "led_type": 19,
  "product_code": "TWS600STP",
  "fw_family": "M",
  "device_name": "Tree out front",
  "uptime": "2768726508",
  "mac": "98:cd:ac:60:ea:01",
  "uuid": "10274000-021F-49E8-81C4-6F776A793F94",
  "max_supported_led": 600,
  "number_of_led": 600,
  "led_profile": "RGB",
  "frame_rate": 9,
  "measured_frame_rate": 9.9,
  "movie_capacity": 992,
  "wire_type": 1,
  "copyright": "LEDWORKS 2021",
  "code": 1000
}
```

**Comment by noremac00662006** [comment]
> And on the top of that - please try to run that code again and make sure that you don't have application on your phone opened.
> 
> (Twinkly is able to communicate only with one device at a time and when you run a script multiple times and/or run at the same time an application which might talk with Twinkly at the same time ... it will fail)

I can confirm that I don't have code running from any other phones or devices.

**Comment by Anders-Holst** [comment]
Sorry for plunging into the discussion, but @scrool, was there not an old bug to this effect, that the mac-address was different in station mode than ap mode or something?
So, @noremac00662006 are you running a version you got with "pip install xled", or the latest version downloaded directly from this repository? If you download it directly here from github, at least that old bug should be fixed. In case it is the same bug. Just to make sure you have the latest version.

**Comment by noremac00662006** [comment]
> Sorry for plunging into the discussion, but @scrool, was there not an old bug to this effect, that the mac-address was different in station mode than ap mode or something? So, @noremac00662006 are you running a version you got with "pip install xled", or the latest version downloaded directly from this repository? If you download it directly here from github, at least that old bug should be fixed. In case it is the same bug. Just to make sure you have the latest version.

@Anders-Holst  I did run "pip install xled" to get the version I was running. I uninstalled the pip version and installed directly from github and success!!! Sorry I did not run across that bug from earlier issues.
