### ISSUE TITLE
Example of movie file/stream?

### ISSUE THREAD

**Issue by DzRepo** [scrool/xled#89]
First: Thanks to all for developing this!
Any good simple examples of how to send a movie using the library?
Another example I could use is how to use RT mode - I thought I saw references to it somewhere but set_mode only supports 'on', 'off', 'movie' and 'demo'. 
Thanks again!

**Comment by scrool** [comment]
RT mode is (in majority?) used with UDP channel which isn't supported by the library nor CLI (yet). There are two PRs - #67 and newer one #80.

If you would like to understand more about modes you could read laungage-independent https://xled-docs.readthedocs.io/

**Comment by DzRepo** [comment]
Thanks for the fast reply. Look forward to an example for the movie - even a bytearray example or something to get me started.

**Comment by Anders-Holst** [comment]
For how to upload a movie, check the file control.py, specifically the functions HighControlInterface.write_static_movie for how to construct an appropriate byte stream, and HighControlInterface.set_static_color for how to upload it to the device.
And now the realtime support mentioned above is checked in too! (Although not yet propagated to pypi, so use the code in this repository.) The function ControlInterface.set_rt_frame_rest and the faster alternative ControlInterface.set_rt_frame_socket takes the same kind of byte streams. Remember to set the mode to "rt" though, with ControlInterface.set_mode.

**Comment by scrool** [comment]
> Look forward to an example for the movie - even a bytearray example or something to get me started.

It greatly depends on what generation of Twinkly you have (first or second), what is number of leds (e.g. 20, 190, 210, 250, ...), what type of LEDs you have (RGB, RGBW, ...) and finally firmware on your device.

For now the best answer would be to check the documentation that I linked earlier and construct binary based on your device(s).

Alternatively you could follow @Anders-Holst advice or his recent MR #91 that tests a lot of calls including movie uploads. It is specific for 250 RGBW - see from this on https://github.com/scrool/xled/pull/91/files#diff-7450efe4388d211d31bf96ecc8c2f9c566fb33d28977c5b3e7ff3b4270072551R90 .
