### ISSUE TITLE
What about adding a Discussion forum for xled in github?

### ISSUE THREAD

**Issue by Anders-Holst** [scrool/xled#93]
There is an option in the Github settings for a Discussion tab. Wouln't that be useful for xled?

Not everything people like to share fits under "issues". It might be that someone needs help, or wants to ask people with different variants of the lights of their experiences, or wants to share experiences, or give tips of how to produce nice effects on their leds.

I think such a possibility would be nice.

  / Anders

**Comment by martincox** [comment]
+1

Just bought a bunch of twinkly lights, glad that I found this library - appreciate all of your effort. 👍🏻 

Would be nice to enable discussions for asking questions, rather than raising issues.

**Comment by scrool** [comment]
> It might be that someone needs help, or wants to ask people with different variants of the lights of their experiences, or wants to share experiences, or give tips of how to produce nice effects on their leds.

> Would be nice to enable discussions for asking questions, rather than raising issues.

For these non-technical questions, which are not directly related to `xled` or [xled-docs](https://github.com/scrool/xled-docs), I advise you to join Facebook group [Twinkly (unofficial users group)](https://www.facebook.com/groups/twinklyusergroup).

**Comment by martincox** [comment]
@scool what about for technical discussions around the api / protocol?

**Comment by scrool** [comment]
> @scrool what about for technical discussions around the api / protocol?

If you are asking about you recent question about z-value of coordinates, that fits better to xled-docs where I moved it https://github.com/scrool/xled-docs/issues/22 .

For now opening an issue might be best option.

There is also https://gitter.im/xled-community/chat which is linked at the very end of https://github.com/scrool/xled/blob/develop/README.rst but I haven't really promoted it more than that.

**Comment by Anders-Holst** [comment]
@scrool wrote:

> For these non-technical questions, which are not directly related to xled or xled-docs, I advise you to join Facebook group...

Too bad that I, for several reasons, boycott Facebook... 
But actually, I do refer to xled - the Twinkly app appears ridiculously limited and inconvenient to use. With xled it becomes possible to create any conceivable effects, making the leds *really* fully programmable in python. That is the kind of stuff I like to discuss, and to exchange hints and code snippets with each other.

**Comment by Anders-Holst** [comment]
For your information, I have now created a Discussion forum on my "sibling-repository" [xled_plus](github.com/Anders-Holst/xled_plus), which we can use to discuss both xled and xled_plus things. It's an experiment. We may see how active it will be. Direct link: https://github.com/Anders-Holst/xled_plus/discussions

**Comment by scrool** [comment]
Now that there is a forum I'm going to close this one for now. We can reopen this later if needed.
